# Generated by Django 6.0.2 on 2026-02-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_unique_id', models.CharField(db_index=True, max_length=50)),
                ('customer_zip_code_prefix', models.CharField(max_length=10)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_state', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'olist_customers',
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_zip_code_prefix', models.CharField(db_index=True, max_length=10)),
                ('geolocation_lat', models.FloatField()),
                ('geolocation_lng', models.FloatField()),
                ('geolocation_city', models.CharField(max_length=100)),
                ('geolocation_state', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'olist_geolocation',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name_length', models.IntegerField(blank=True, null=True)),
                ('product_description_length', models.IntegerField(blank=True, null=True)),
                ('product_photos_qty', models.IntegerField(blank=True, null=True)),
                ('product_weight_g', models.IntegerField(blank=True, null=True)),
                ('product_length_cm', models.IntegerField(blank=True, null=True)),
                ('product_height_cm', models.IntegerField(blank=True, null=True)),
                ('product_width_cm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'olist_products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryTranslation',
            fields=[
                ('product_category_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_category_name_english', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_category_translation',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seller_zip_code_prefix', models.CharField(max_length=10)),
                ('seller_city', models.CharField(max_length=100)),
                ('seller_state', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'olist_sellers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=20)),
                ('order_purchase_timestamp', models.DateTimeField(blank=True, null=True)),
                ('order_approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_carrier_date', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_customer_date', models.DateTimeField(blank=True, null=True)),
                ('order_estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.customer')),
            ],
            options={
                'db_table': 'olist_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sequential', models.IntegerField()),
                ('payment_type', models.CharField(max_length=30)),
                ('payment_installments', models.IntegerField()),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='warehouse.order')),
            ],
            options={
                'db_table': 'olist_order_payments',
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=50)),
                ('review_score', models.IntegerField()),
                ('review_comment_title', models.TextField(blank=True, null=True)),
                ('review_comment_message', models.TextField(blank=True, null=True)),
                ('review_creation_date', models.DateTimeField(blank=True, null=True)),
                ('review_answer_timestamp', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='warehouse.order')),
            ],
            options={
                'db_table': 'olist_order_reviews',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField()),
                ('shipping_limit_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='warehouse.product')),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='warehouse.seller')),
            ],
            options={
                'db_table': 'olist_order_items',
            },
        ),
    ]
